services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      FLASK_APP: manager.py

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: root

    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33067:3306"

    